<a href="https://colab.research.google.com/github/HariGodGamer/Summer-BootCamp-1st-Year/blob/main/Summer%20BootCamp%20Session%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Calculate Class Average and Status
This code block initializes a list of student marks. It then attempts to calculate the total sum of marks and the average. **Note:** The loop `for i in range(len(marks) - 1)` will iterate one element less than the actual length, causing the last mark to be excluded from the total sum. This will result in an incorrect average. After calculation, it determines if the class passed or failed based on whether the average is above 50.

In [20]:
marks = [45, 60, 72, 38, 90]

total = 0

for i in range(len(marks) - 1):
    total += marks[i]

average = total / len(marks)

if average > 50:
    print("Class passed")
else:
    print("Class failed")

print("Average:", average)

Class failed
Average: 43.0

### Import Libraries
This cell imports the `pandas` library, which is essential for working with data structures like DataFrames.

In [21]:
import pandas as pd

### Prepare Student Data
This code block defines a dictionary named `data` that contains information for several students, including their ID, attendance percentage, assignment score, quiz score, and whether they completed the lab. This data will be used to create a DataFrame.

In [22]:
data = {
    "student_id": [101, 102, 103, 104, 105, 106],
    "attendance_percent": [92, 67, 81, 45, 74, 88],
    "assignment_score": [18, 12, 15, 8, 14, 19],
    "quiz_score": [72, 48, 65, 30, 55, 80],
    "lab_completed": [True, False, True, False, True, True]
}

### Create DataFrame
This cell converts the `data` dictionary into a pandas DataFrame named `df`. This structured format makes it easier to manipulate and analyze the student data.

In [23]:
df = pd.DataFrame(data)
df

   student_id  attendance_percent  assignment_score  quiz_score  lab_completed
0         101                  92                18          72           True
1         102                  67                12          48          False
2         103                  81                15          65           True
3         104                  45                 8          30          False
4         105                  74                14          55           True
5         106                  88                19          80           True

### Display DataFrame Shape
This cell prints the shape of the DataFrame `df`, which indicates the number of rows (students) and columns (features) in the dataset.

In [24]:
df.shape

(6, 5)

### Display First Few Rows of DataFrame
This cell displays the first few rows of the `df` DataFrame using `df.head()`, which is useful for a quick overview of the data and its structure.

In [25]:
df.head()

   student_id  attendance_percent  assignment_score  quiz_score  lab_completed
0         101                  92                18          72           True
1         102                  67                12          48          False
2         103                  81                15          65           True
3         104                  45                 8          30          False
4         105                  74                14          55           True

### Get DataFrame Information
This cell provides a concise summary of the DataFrame `df` using `df.info()`. It includes the data types of each column, the number of non-null values, and memory usage, which is helpful for initial data assessment.

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          6 non-null      int64
 1   attendance_percent  6 non-null      int64
 2   assignment_score    6 non-null      int64
 3   quiz_score          6 non-null      int64
 4   lab_completed       6 non-null      bool
dtypes: bool(1), int64(4)
memory usage: 330.0 bytes

### Generate Descriptive Statistics
This cell calculates and displays descriptive statistics for the numerical columns in the DataFrame `df` using `df.describe()`. This includes count, mean, standard deviation, min, max, and quartile values, giving insights into the data distribution.

In [27]:
df.describe()

       student_id  attendance_percent  assignment_score  quiz_score
count    6.000000            6.000000          6.000000    6.000000
mean   103.500000           74.500000         14.333333   58.333333
std      1.870829           17.073371          4.033196   18.007406
min    101.000000           45.000000          8.000000   30.000000
25%    102.250000           68.750000         12.500000   49.750000
50%    103.500000           77.500000         14.500000   60.000000
75%    104.750000           86.250000         17.250000   70.250000
max    106.000000           92.000000         19.000000   80.000000

### Calculate Total Score
This code block creates a new column named `total_score` in the DataFrame `df`. This score is calculated by summing the `assignment_score` and `quiz_score` for each student.

In [28]:
df['total_score'] = df['assignment_score'] + df['quiz_score']
df

,student_id,attendance_percent,assignment_score,quiz_score,lab_completed,total_score
0,101,92,18,72,True,90
1,102,67,12,48,False,60
2,103,81,15,65,True,80
3,104,45,8,30,False,38
4,105,74,14,55,True,69
5,106,88,19,80,True,99

### Determine Student Eligibility
This cell adds a new boolean column `eligible` to the DataFrame `df`. A student is considered eligible if their `attendance_percent` is 75% or higher, their `total_score` is 70 or higher, AND they have `lab_completed`.

In [29]:
df['eligible'] = (
    (df['attendance_percent'] >= 75) &
    (df['total_score'] >= 70) &
    (df['lab_completed'])
)
df

,student_id,attendance_percent,assignment_score,quiz_score,lab_completed,total_score,eligible
0,101,92,18,72,True,90,True
1,102,67,12,48,False,60,False
2,103,81,15,65,True,80,True
3,104,45,8,30,False,38,False
4,105,74,14,55,True,69,False
5,106,88,19,80,True,99,True

### Filter for Eligible Students
This code block creates a new DataFrame called `eligible_students` by filtering the original `df` DataFrame. It selects only those rows where the `eligible` column is `True`, effectively listing all students who meet the eligibility criteria.

In [30]:
eligible_students = df[df["eligible"] == True]
eligible_students

,student_id,attendance_percent,assignment_score,quiz_score,lab_completed,total_score,eligible
0,101,92,18,72,True,90,True
2,103,81,15,65,True,80,True
5,106,88,19,80,True,99,True